modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Stalemated/custom-tooltip-api/issues"
license = "MIT"
clientSideOnly = true

[[mods]]
modId = "customtooltips"
version = "${version}"
displayName = "Custom Tooltip API"
authors = "Stalemated"
description = '''
A completely customizable, tag-based tooltip manager for developers and modpack makers.
'''
logoFile = "META-INF/icon.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/custom-tooltip-api"


[[mixins]]
config = "customtooltips.mixins.json"

[[mixins]]
config = "customtooltips-neoforge.mixins.json"

[[dependencies.customtooltips]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.customtooltips]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.customtooltips]]
modId = "s_lib"
type = "required"
versionRange = "[1.0.2+1.21.1,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.customtooltips]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.8.2,)"
ordering = "AFTER"
side = "CLIENT"
